import { Module, CategoryInfo } from '../types';

export const MODULES: Module[] = [
  // Калькуляторы
  {
    id: 'pressure',
    title: 'Калькулятор давления',
    description: 'Расчёт давления воды в системе с учётом высоты и потерь',
    icon: 'Gauge',
    path: '/calculators/pressure',
    category: 'calculators',
  },
  {
    id: 'pipe-diameter',
    title: 'Диаметр труб',
    description: 'Подбор диаметра трубы по расходу и скорости потока',
    icon: 'CircleDot',
    path: '/calculators/pipe-diameter',
    category: 'calculators',
  },
  {
    id: 'water-flow',
    title: 'Расход воды',
    description: 'Расчёт расхода воды по сечению трубы и скорости',
    icon: 'Droplets',
    path: '/calculators/water-flow',
    category: 'calculators',
  },
  {
    id: 'heat-loss',
    title: 'Теплопотери',
    description: 'Расчёт теплопотерь через трубопровод',
    icon: 'Thermometer',
    path: '/calculators/heat-loss',
    category: 'calculators',
    isNew: true,
  },
  // Справочники
  {
    id: 'materials',
    title: 'Материалы труб',
    description: 'Справочник по материалам: сталь, медь, полипропилен, PEX',
    icon: 'Package',
    path: '/reference/materials',
    category: 'reference',
  },
  {
    id: 'boiler-errors',
    title: 'Ошибки котлов',
    description: 'Коды ошибок Baxi, Vaillant, Bosch, Navien, Protherm',
    icon: 'AlertTriangle',
    path: '/reference/boiler-errors',
    category: 'reference',
    isNew: true,
  },
  {
    id: 'troubleshooting',
    title: 'Диагностика по симптомам',
    description: 'Пошаговая диагностика проблем',
    icon: 'Stethoscope',
    path: '/reference/troubleshooting',
    category: 'reference',
    isNew: true,
  },
  {
    id: 'units-converter',
    title: 'Конвертер единиц',
    description: 'Перевод единиц давления, расхода, температуры',
    icon: 'ArrowLeftRight',
    path: '/tools/units-converter',
    category: 'tools',
  },
  {
    id: 'pipe-length',
    title: 'Длина трубопровода',
    description: 'Расчёт длины трубы с учётом фитингов (эквивалентная длина)',
    icon: 'Ruler',
    path: '/calculators/pipe-length',
    category: 'calculators',
  },
  {
    id: 'slope',
    title: 'Уклон канализации',
    description: 'Расчёт уклона канализационной трубы по нормативам СП 30.13330.2020',
    icon: 'TrendingDown',
    path: '/calculators/slope',
    category: 'calculators',
    isNew: true,
  },
  // Проектирование
  {
    id: 'design-pipe-diameter',
    title: 'Диаметр трубы (инж.)',
    description: 'Инженерный расчёт диаметра трубы по расходу',
    icon: 'Droplets',
    path: '/design/pipe-diameter',
    category: 'design',
    isNew: true,
  },
  {
    id: 'design-pump',
    title: 'Циркуляционный насос',
    description: 'Подбор насоса по производительности и напору',
    icon: 'CircleDot',
    path: '/design/pump',
    category: 'design',
    isNew: true,
  },
  {
    id: 'design-expansion-tank',
    title: 'Расширительный бак',
    description: 'Расчёт объёма расширительного бака',
    icon: 'Gauge',
    path: '/design/expansion-tank',
    category: 'design',
    isNew: true,
  },
  {
    id: 'design-radiator',
    title: 'Расчёт радиаторов',
    description: 'Подбор мощности и количества секций',
    icon: 'Flame',
    path: '/design/radiator',
    category: 'design',
    isNew: true,
  },
];

export const CATEGORIES: CategoryInfo[] = [
  { id: 'calculators', title: 'Калькуляторы', icon: 'Calculator' },
  { id: 'reference', title: 'Справочники', icon: 'BookOpen' },
  { id: 'tools', title: 'Инструменты', icon: 'Wrench' },
  { id: 'planning', title: 'Планирование', icon: 'ClipboardList' },
  { id: 'design', title: 'Проектирование', icon: 'Ruler' },
];
